### ISSUE TITLE
Error installing on Mac

### ISSUE THREAD

**Issue by woody4165** [ruimarinho/shelly-updater#2]
Hi

Thanks for sharing your project.

I'm trying to install on a Mac with HighSierra (10.13.6), but I'm getting this error

```
$ brew install mota
Error: undefined method `license' for Formulary::FormulaNamespacee8b3030d6516555880e27122ccebc984::Mota:Class
Please report this bug:
    https://git.io/brew-troubleshooting
/usr/local/Library/Taps/ruimarinho/homebrew-tap/Formula/mota.rb:9:in `<class:Mota>'
/usr/local/Library/Taps/ruimarinho/homebrew-tap/Formula/mota.rb:5:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
/usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
/usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
/usr/local/Library/Homebrew/formulary.rb:85:in `load_file'
/usr/local/Library/Homebrew/formulary.rb:76:in `klass'
/usr/local/Library/Homebrew/formulary.rb:72:in `get_formula'
/usr/local/Library/Homebrew/formulary.rb:207:in `factory'
/usr/local/Library/Homebrew/formulary.rb:352:in `find_with_priority'
/usr/local/Library/Homebrew/extend/ARGV.rb:20:in `block in formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:45:in `install'
/usr/local/Library/brew.rb:143:in `<main>'

```

what can I check?

Thanks

**Comment by ruimarinho** [comment]
Hi @woody4165. Can you run `brew --version`? You're likely running a very outdated version of brew.

**Comment by woody4165** [comment]
Running on MacOS High Sierra (late 2017), the brew version is 0.9.5
Is there a way to upgrade only brew, since my iMac cannot go over this OSX version?

**Comment by ruimarinho** [comment]
Looking at https://github.com/Homebrew/brew/pull/6500, you could try updating to 2.1.0, which seems to be the latest support High Sierra.
